# Generated by Django 4.2.13 on 2024-07-08 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='isUser',
            field=models.BooleanField(default=False),
        ),
    ]
